import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Simulation} from '../.test-build/sim.js';
import {Inventory} from '../.test-build/inventory.js';
test('grid moves reject overlap and boundary overflow without losing supplies',()=>{const s=new Simulation(),m=new Inventory(s);const water=m.stacks.find(a=>a.kind==='Water');const beans=m.stacks.find(a=>a.kind==='Beans');assert.equal(m.move(water.id,'backpack',5,4),false);assert.equal(m.move(water.id,'backpack',beans.x,beans.y),false);assert.equal(s.bag.Water,1);assert.equal(m.move(water.id,'backpack',4,2),true);assert.equal(water.x,4);});
test('stash transfers remove carried supplies and retrieval restores them',()=>{const s=new Simulation(),m=new Inventory(s),a=m.stacks.find(a=>a.kind==='Water');assert.equal(m.move(a.id,'stash',2,2),true);assert.equal(s.bag.Water,0);assert.equal(m.stash.Water,1);s.use('Water');assert.equal(m.stash.Water,1);assert.equal(m.transfer(a.id),true);assert.equal(s.bag.Water,1);assert.equal(m.stash.Water,0);});
test('ammunition storage changes reload reserves and stored stacks merge with new loot',()=>{const s=new Simulation(),m=new Inventory(s),ammo=m.stacks.find(a=>a.kind==='Ammo');m.transfer(ammo.id);assert.equal(s.reserve,0);assert.equal(m.stash.Ammo,24);m.transfer(ammo.id);assert.equal(s.reserve,24);const water=m.stacks.find(a=>a.kind==='Water');m.transfer(water.id);s.bag.Water=2;m.sync();const fresh=m.stacks.find(a=>a.kind==='Water'&&a.container!=='stash');assert.equal(m.move(fresh.id,'stash',water.x,water.y),true);assert.equal(m.stash.Water,3);assert.equal(s.bag.Water,0);assert.equal(m.stacks.filter(a=>a.kind==='Water').length,1);});
test('layout survives reopening and consuming removes only depleted stacks',()=>{const s=new Simulation(),m=new Inventory(s),beans=m.stacks.find(a=>a.kind==='Beans');m.move(beans.id,'pockets',5,1);m.sync();assert.equal(beans.container,'pockets');assert.equal(beans.x,5);s.use('Beans');m.sync();assert.ok(!m.stacks.some(a=>a.id===beans.id));assert.ok(m.stacks.some(a=>a.kind==='Water'));});
test('inventory can equip while the world stays paused',()=>{const s=new Simulation();s.paused=true;s.equip('rifle');assert.equal(s.weapon,'bat');s.equip('rifle',true);assert.equal(s.weapon,'rifle');assert.equal(s.paused,true);});
