import {InventoryPreview} from './inventory-preview';
import {CLOTHING,clothingKind,type ClothingSlot} from './wardrobe';
import {itemArt} from './sprite-assets';
import {Inventory,ITEM_INFO,GRIDS,type ArmorKind,type Container} from './inventory';
import type {Simulation} from './sim';
export class InventoryScreen{
 preview?:InventoryPreview;
 model:Inventory;selected='';notice='Drag items to arrange your gear. Select supplies, then choose USE ITEM.';dragging=false;
 constructor(public s:Simulation,public icon:(name:string)=>string){this.model=s.inventory;}
 updatePreview(){this.preview?.render();}
 art(name:string){return itemArt(name)||this.icon(name);}
 render(root:HTMLElement,close:()=>void){this.model.sync();const m=this.model,s=this.s;const selected=m.stacks.find(a=>a.id===this.selected);
 const grid=(name:Container)=>{const g=GRIDS[name];return `<div class="gear-grid" data-grid="${name}" style="--cols:${g.w};--rows:${g.h}" role="group" aria-label="${name} storage">${Array.from({length:g.w*g.h},(_,i)=>`<button class="gear-cell" style="grid-column:${i%g.w+1};grid-row:${Math.floor(i/g.w)+1}" data-cell="${name}" data-x="${i%g.w}" data-y="${Math.floor(i/g.w)}" aria-label="${name} column ${i%g.w+1} row ${Math.floor(i/g.w)+1}"></button>`).join('')}${m.stacks.filter(a=>a.container===name).map(a=>{const info=ITEM_INFO[a.kind];return `<button class="gear-item ${a.kind.toLowerCase()} ${a.id===this.selected?'selected':''}" data-stack="${a.id}" style="grid-column:${a.x+1}/span ${info.w};grid-row:${a.y+1}/span ${info.h}" aria-label="${info.name}, ${m.quantity(a)}, ${name}"><span>${info.name}</span>${this.art(info.icon)}<b>×${m.quantity(a)}</b></button>`;}).join('')}</div>`;};
 const weapon=(slot:'hands'|'back')=>{const type=slot==='hands'?s.weapon:s.weapon==='bat'?'rifle':'bat';if(type==='rifle'&&!s.ownedGuns.length)return '<div class="weapon-slot"><span class="gear-label">ON BACK</span><small>No firearm found yet</small></div>';return `<div class="weapon-slot" data-slot="${slot}" role="group" aria-label="${slot==='hands'?'In hands':'On back'} weapon slot"><span class="gear-label">${slot==='hands'?'IN HANDS':'ON BACK'} <small>${slot==='hands'?'ACTIVE':'SLUNG'}</small></span><button class="equipped-weapon" data-weapon="${type}" aria-label="${type==='rifle'?s.firearm.name:s.meleeName} ${slot==='hands'?'in hands':'on back'}">${this.art(type==='rifle'?({carbine:'rifle',pistol:'Pistol',shotgun:'Shotgun',hunting:'HuntingRifle',smg:'SMG'}[s.gun]):s.meleeIcon)}<strong>${type==='rifle'?s.firearm.name:s.meleeName}</strong><b>${type==='rifle'?s.ammo+' / '+s.firearm.capacity:Math.ceil(s.life.batCondition)+'%'}</b></button></div>`;};
 const armorSlot=(kind:ArmorKind)=>`<div class="empty-gear armor-slot" data-armor-slot="${kind}"><span>${kind==='helmet'?'HEADWEAR':'BODY ARMOR'}</span>${s.armorEquipped[kind]?`<button class="equipped-armor" data-equipped-armor="${kind}" aria-label="${ITEM_INFO[kind].name}, drag to storage">${this.art(kind)}<strong>${ITEM_INFO[kind].name}</strong><small><span data-armor="${kind}">${Math.ceil(s.armor[kind])}</span>% condition</small></button>`:'<small>Empty · Drag armor here</small>'}</div>`;
 const clothingSlot=(slot:ClothingSlot)=>{const kind=s.outfit[slot];return `<div class="clothing-slot" data-clothing-slot="${slot}"><span>${slot==='top'?'UPPER BODY':'TROUSERS'}</span>${kind?`<button data-worn-clothes="${slot}">${this.art(kind)}<strong>${CLOTHING[kind].name}</strong><small>Right-click to take off</small></button>`:'<small>Base layer · Drag clothes here</small>'}</div>`;};
 root.innerHTML=`<section class="gear-screen" role="dialog" aria-modal="true" aria-label="Inventory management"><header class="gear-header"><div class="gear-brand">ASH COUNTY <span>/ SURVIVOR</span></div><span class="gear-tab">${this.icon('bag')} GEAR</span><span class="gear-paused">● WORLD LIVE</span><button id="gear-close">BACK <kbd>I / ESC</kbd> ×</button></header><div class="gear-body"><section class="survivor-preview-column"><div class="gear-section-title">YOUR SURVIVOR <span>LIVE 3D VIEW</span></div><div class="survivor-preview" id="survivor-preview"></div><p class="preview-hint">DRAG TO ROTATE · GEAR UPDATES LIVE</p><div class="clothing-slots">${clothingSlot('top')}${clothingSlot('bottom')}</div></section><section class="equipment-column"><div class="gear-section-title">EQUIPMENT <span>01 / ALEX MORGAN</span></div><div class="equipment-body">${armorSlot('helmet')}${armorSlot('kevlar')}${weapon('hands')}${weapon('back')}<div class="worn-pack">${this.art('bag')}<div>CANVAS BACKPACK<small>48 storage cells · Equipped</small></div></div></div><div class="gear-vitals"><span>${this.icon('heart')} <b data-gear-health>${Math.ceil(s.player.hp)}</b><small>HEALTH</small></span><span>${this.icon('water')} <b data-gear-thirst>${Math.ceil(s.player.thirst)}</b><small>HYDRATION</small></span><span>${m.weight.toFixed(1)}<small>KG / 42 MAX</small></span></div></section><section class="carry-column"><div class="gear-section-title">POCKETS <span>QUICK ACCESS</span></div>${grid('pockets')}<div class="gear-section-title backpack-title">BACKPACK <span>CANVAS · 8 × 6</span></div>${grid('backpack')}<div class="gear-tip">${this.icon('compass')} Keep essentials close.<br><span>Drag armor to storage to remove it, or back to its equipment slot to wear it.</span></div></section></div><footer class="gear-footer"><div class="item-detail"><strong>${selected?ITEM_INFO[selected.kind].name:'YOUR GEAR. YOUR WAY.'}</strong><span id="gear-notice">${this.notice}</span></div><div class="gear-actions"><button id="gear-use" ${!selected||selected.kind in s.life.ammo?'disabled':''}>${selected&&s.survival.packed.has(selected.kind)?'PLACE IN WORLD':'USE ITEM'}</button><button id="gear-clear" ${!selected?'disabled':''}>CANCEL</button></div><small>DRAG TO MOVE · RIGHT-CLICK FURNITURE TO PLACE</small></footer></section>`;
 (this.preview??=new InventoryPreview(s)).mount(root.querySelector<HTMLElement>('#survivor-preview')!);
 root.querySelector<HTMLButtonElement>('#gear-close')!.onclick=close;
 const redraw=()=>this.render(root,close);const message=(text:string)=>{this.notice=text;root.querySelector('#gear-notice')!.textContent=text;};
 root.querySelector<HTMLButtonElement>('#gear-clear')!.onclick=()=>{this.selected='';redraw();};
 const use=()=>{const a=m.stacks.find(a=>a.id===this.selected);if(a&&a.kind!=='Ammo'){s.use(a.kind);this.notice=s.message;m.sync();redraw();}};
 root.querySelector<HTMLButtonElement>('#gear-use')!.onclick=use;
 const drop=(id:string,x:number,y:number,weaponType?:string,offsetX=0,offsetY=0)=>{const el=document.elementFromPoint(x,y) as HTMLElement|null;if(weaponType){const slot=el?.closest<HTMLElement>('[data-slot]');if(slot){s.equip(slot.dataset.slot==='hands'?weaponType as 'bat'|'rifle':weaponType==='bat'?'rifle':'bat',true);this.notice='Weapon equipped.';}else this.notice='Weapons belong in IN HANDS or ON BACK.';redraw();return;}
 const clothingTarget=el?.closest<HTMLElement>('[data-clothing-slot]'),clothingStack=m.stacks.find(a=>a.id===id);if(clothingTarget&&clothingStack&&clothingKind(clothingStack.kind)){this.notice=CLOTHING[clothingStack.kind].slot===clothingTarget.dataset.clothingSlot&&m.wear(clothingStack.kind)?'Clothing changed.':'Use the matching clothing slot and leave room for your old clothes.';this.selected='';redraw();return;}
 const armorTarget=el?.closest<HTMLElement>('[data-armor-slot]'),stack=m.stacks.find(a=>a.id===id);
 if(armorTarget){const kind=stack?.kind;if((kind==='helmet'||kind==='kevlar')&&armorTarget.dataset.armorSlot===kind){this.notice=m.equipArmor(kind)?'Armor equipped.':'That armor slot is occupied.';this.selected='';}else this.notice='Use the matching armor slot.';redraw();return;}
 const armor=id.startsWith('armor:')?id.slice(6) as ArmorKind:undefined;
 const item=el?.closest<HTMLElement>('[data-stack]');const target=item?m.stacks.find(a=>a.id===item.dataset.stack):null;const board=el?.closest<HTMLElement>('[data-grid]');if(!board){message('Drop inside a storage grid.');return;}const rect=board.getBoundingClientRect(),container=board.dataset.grid as Container,g=GRIDS[container];const info=ITEM_INFO[armor||m.stacks.find(a=>a.id===id)!.kind];if(armor){offsetX=0;offsetY=0;}const tx=Math.max(0,Math.min(g.w-info.w,Math.round((x-offsetX-rect.left)/rect.width*g.w))),ty=Math.max(0,Math.min(g.h-info.h,Math.round((y-offsetY-rect.top)/rect.height*g.h)));this.notice=armor?(m.stowArmor(armor,container,tx,ty)?'Armor moved to storage.':'Not enough free space there. Armor stays equipped.'):(m.move(id,container,tx,ty)?'Item moved.':'That space is occupied or too small. Choose an empty area.');this.selected=armor?'':id;redraw();};
 const dismissMenu=()=>root.querySelector('.inventory-object-menu')?.remove();
 root.onpointerdown=e=>{if(!(e.target as HTMLElement).closest('.inventory-object-menu'))dismissMenu();};
 root.onkeydown=e=>{if(e.key==='Escape')dismissMenu();};
 root.querySelectorAll<HTMLElement>('[data-stack],[data-weapon],[data-equipped-armor]').forEach(el=>{
 el.oncontextmenu=e=>{
  if(!el.dataset.stack)return;const stack=m.stacks.find(a=>a.id===el.dataset.stack);if(!stack||!s.survival.packed.has(stack.kind)&&!clothingKind(stack.kind))return;
  e.preventDefault();e.stopPropagation();dismissMenu();this.selected=stack.id;
  const menu=document.createElement('div');menu.className='object-menu inventory-object-menu';menu.setAttribute('role','menu');
  const title=document.createElement('strong');title.textContent=ITEM_INFO[stack.kind].name;
  const place=document.createElement('button');place.textContent=clothingKind(stack.kind)?'Wear':'Place in world';place.setAttribute('role','menuitem');
  place.onclick=()=>{dismissMenu();if(clothingKind(stack.kind)){message(m.wear(stack.kind)?'Clothing changed.':'Make room for your current clothes.');redraw();}else s.survival.placeFromInventory(stack.kind);};menu.append(title,place);root.append(menu);
  menu.style.left=Math.max(8,Math.min(e.clientX,innerWidth-244))+'px';menu.style.top=Math.max(8,Math.min(e.clientY,innerHeight-menu.offsetHeight-8))+'px';place.focus();
 };

 el.onpointerdown=e=>{
  if(e.button!==0)return;e.preventDefault();const startX=e.clientX,startY=e.clientY,r=el.getBoundingClientRect();
  let ghost:HTMLElement|undefined;const offsetX=e.clientX-r.left,offsetY=e.clientY-r.top;
  const cleanup=()=>{ghost?.remove();this.dragging=false;window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);window.removeEventListener('pointercancel',cancel);window.removeEventListener('blur',cancel);};
  const move=(event:PointerEvent)=>{if(event.pointerId!==e.pointerId)return;
   if(!ghost&&Math.hypot(event.clientX-startX,event.clientY-startY)>5){ghost=el.cloneNode(true) as HTMLElement;ghost.removeAttribute('data-stack');ghost.classList.add('gear-drag-ghost');Object.assign(ghost.style,{width:r.width+'px',height:r.height+'px'});document.body.append(ghost);this.dragging=true;}
   if(ghost){ghost.style.left=event.clientX-offsetX+'px';ghost.style.top=event.clientY-offsetY+'px';}
  };
  const end=(event:PointerEvent)=>{if(event.pointerId!==e.pointerId)return;const dragged=!!ghost;cleanup();
   if(dragged)drop(el.dataset.equippedArmor?'armor:'+el.dataset.equippedArmor:el.dataset.stack||'',event.clientX,event.clientY,el.dataset.weapon,offsetX,offsetY);
   else if(el.dataset.stack){this.selected=el.dataset.stack;this.notice=ITEM_INFO[m.stacks.find(a=>a.id===this.selected)!.kind].desc;redraw();}
   else if(el.dataset.weapon){s.equip(el.dataset.weapon as 'bat'|'rifle',true);redraw();}
  };
  const cancel=()=>cleanup();window.addEventListener('pointermove',move);window.addEventListener('pointerup',end);window.addEventListener('pointercancel',cancel);window.addEventListener('blur',cancel);
 };

 el.ondblclick=()=>{if(el.dataset.stack){this.selected=el.dataset.stack;use();}};
 el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();if(el.dataset.stack){this.selected=el.dataset.stack;this.notice=ITEM_INFO[m.stacks.find(a=>a.id===this.selected)!.kind].desc;redraw();}else if(el.dataset.weapon){s.equip(el.dataset.weapon as 'bat'|'rifle',true);redraw();}else{message('Drag this armor into a free storage area to remove it.');}}};});
 root.querySelectorAll<HTMLButtonElement>('[data-worn-clothes]').forEach(button=>{button.oncontextmenu=e=>{e.preventDefault();dismissMenu();const menu=document.createElement('div');menu.className='object-menu inventory-object-menu';const remove=document.createElement('button');remove.textContent='Take off';remove.onclick=()=>{this.notice=m.undress(button.dataset.wornClothes as ClothingSlot)?'Clothes moved to inventory.':'Not enough space in inventory.';redraw();};menu.append(remove);root.append(menu);menu.style.left=Math.min(e.clientX,innerWidth-244)+'px';menu.style.top=Math.min(e.clientY,innerHeight-60)+'px';};});
 root.querySelectorAll<HTMLButtonElement>('[data-cell]').forEach(cell=>cell.onclick=()=>{if(!this.selected)return;this.notice=m.move(this.selected,cell.dataset.cell as Container,Number(cell.dataset.x),Number(cell.dataset.y))?'Item moved.':'That space is occupied or too small.';redraw();});
 }
}
