import {itemArt} from './sprite-assets';
import {Inventory,ITEM_INFO,GRIDS,type Container} from './inventory';
import type {Simulation} from './sim';
export class InventoryScreen{
 model:Inventory;selected='';notice='Drag items to arrange your gear. Select supplies, then choose USE ITEM.';dragging=false;
 constructor(public s:Simulation,public icon:(name:string)=>string){this.model=s.inventory;}
 art(name:string){return itemArt(name)||this.icon(name);}
 render(root:HTMLElement,close:()=>void){this.model.sync();const m=this.model,s=this.s;const selected=m.stacks.find(a=>a.id===this.selected);
 const grid=(name:Container)=>{const g=GRIDS[name];return `<div class="gear-grid" data-grid="${name}" style="--cols:${g.w};--rows:${g.h}" role="group" aria-label="${name} storage">${Array.from({length:g.w*g.h},(_,i)=>`<button class="gear-cell" style="grid-column:${i%g.w+1};grid-row:${Math.floor(i/g.w)+1}" data-cell="${name}" data-x="${i%g.w}" data-y="${Math.floor(i/g.w)}" aria-label="${name} column ${i%g.w+1} row ${Math.floor(i/g.w)+1}"></button>`).join('')}${m.stacks.filter(a=>a.container===name).map(a=>{const info=ITEM_INFO[a.kind];return `<button class="gear-item ${a.kind.toLowerCase()} ${a.id===this.selected?'selected':''}" data-stack="${a.id}" style="grid-column:${a.x+1}/span ${info.w};grid-row:${a.y+1}/span ${info.h}" aria-label="${info.name}, ${m.quantity(a)}, ${name}"><span>${info.name}</span>${this.art(info.icon)}<b>×${m.quantity(a)}</b></button>`;}).join('')}</div>`;};
 const weapon=(slot:'hands'|'back')=>{const type=slot==='hands'?s.weapon:s.weapon==='bat'?'rifle':'bat';return `<div class="weapon-slot" data-slot="${slot}" role="group" aria-label="${slot==='hands'?'In hands':'On back'} weapon slot"><span class="gear-label">${slot==='hands'?'IN HANDS':'ON BACK'} <small>${slot==='hands'?'ACTIVE':'SLUNG'}</small></span><button class="equipped-weapon" data-weapon="${type}" aria-label="${type==='rifle'?s.firearm.name:'Wooden bat'} ${slot==='hands'?'in hands':'on back'}">${this.art(type==='rifle'?({carbine:'rifle',pistol:'Pistol',shotgun:'Shotgun',hunting:'HuntingRifle',smg:'SMG'}[s.gun]):'bat')}<strong>${type==='rifle'?s.firearm.name:'Wooden bat'}</strong><b>${type==='rifle'?s.ammo+' / '+s.firearm.capacity:'100%'}</b></button></div>`;};
 root.innerHTML=`<section class="gear-screen" role="dialog" aria-modal="true" aria-label="Inventory management"><header class="gear-header"><div class="gear-brand">ASH COUNTY <span>/ SURVIVOR</span></div><span class="gear-tab">${this.icon('bag')} GEAR</span><span class="gear-paused">● WORLD PAUSED</span><button id="gear-close">BACK <kbd>I / ESC</kbd> ×</button></header><div class="gear-body"><section class="equipment-column"><div class="gear-section-title">EQUIPMENT <span>01 / ALEX MORGAN</span></div><div class="equipment-body"><svg class="body-outline" viewBox="0 0 200 320"><g fill="#77847122" stroke="#a7b39825"><ellipse cx="100" cy="36" rx="23" ry="29"/><path d="m77 62-28 15-27 108 16 5 38-85-9 100 13 99h17l3-87 9 87h17l8-99-8-100 34 85 17-5-28-108-25-15Z"/></g></svg><div class="empty-gear"><span>HEADWEAR</span><i>—</i><small>No head protection</small></div><div class="empty-gear"><span>BODY ARMOR</span><i>—</i><small>No armor equipped</small></div>${weapon('hands')}${weapon('back')}<div class="worn-pack">${this.art('bag')}<div>CANVAS BACKPACK<small>48 storage cells · Equipped</small></div></div></div><div class="gear-vitals"><span>${this.icon('heart')} ${Math.ceil(s.player.hp)}<small>HEALTH</small></span><span>${this.icon('water')} ${Math.ceil(s.player.thirst)}<small>HYDRATION</small></span><span>${m.weight.toFixed(1)}<small>KG CARRIED</small></span></div></section><section class="carry-column"><div class="gear-section-title">POCKETS <span>QUICK ACCESS</span></div>${grid('pockets')}<div class="gear-section-title backpack-title">BACKPACK <span>CANVAS · 8 × 6</span></div>${grid('backpack')}<div class="gear-tip">${this.icon('compass')} Keep essentials close.<br><span>Drag a weapon between IN HANDS and ON BACK to equip it.</span></div></section></div><footer class="gear-footer"><div class="item-detail"><strong>${selected?ITEM_INFO[selected.kind].name:'YOUR GEAR. YOUR WAY.'}</strong><span id="gear-notice">${this.notice}</span></div><div class="gear-actions"><button id="gear-use" ${!selected||selected.kind==='Ammo'?'disabled':''}>${selected&&s.survival.packed.has(selected.kind)?'PLACE IN WORLD':'USE ITEM'}</button><button id="gear-clear" ${!selected?'disabled':''}>CANCEL</button></div><small>DRAG TO MOVE · CLICK ITEM + CELL TO PLACE</small></footer></section>`;
 root.querySelector<HTMLButtonElement>('#gear-close')!.onclick=close;
 const redraw=()=>this.render(root,close);const message=(text:string)=>{this.notice=text;root.querySelector('#gear-notice')!.textContent=text;};
 root.querySelector<HTMLButtonElement>('#gear-clear')!.onclick=()=>{this.selected='';redraw();};
 const use=()=>{const a=m.stacks.find(a=>a.id===this.selected);if(a&&a.kind!=='Ammo'){s.use(a.kind);this.notice=s.message;m.sync();redraw();}};
 root.querySelector<HTMLButtonElement>('#gear-use')!.onclick=use;
 const drop=(id:string,x:number,y:number,weaponType?:string,offsetX=0,offsetY=0)=>{const el=document.elementFromPoint(x,y) as HTMLElement|null;if(weaponType){const slot=el?.closest<HTMLElement>('[data-slot]');if(slot){s.equip(slot.dataset.slot==='hands'?weaponType as 'bat'|'rifle':weaponType==='bat'?'rifle':'bat',true);this.notice='Weapon equipped.';}else this.notice='Weapons belong in IN HANDS or ON BACK.';redraw();return;}
 const item=el?.closest<HTMLElement>('[data-stack]');const target=item?m.stacks.find(a=>a.id===item.dataset.stack):null;const board=el?.closest<HTMLElement>('[data-grid]');if(!board){message('Drop inside a storage grid.');return;}const rect=board.getBoundingClientRect(),container=board.dataset.grid as Container,g=GRIDS[container];const info=ITEM_INFO[m.stacks.find(a=>a.id===id)!.kind];const tx=Math.max(0,Math.min(g.w-info.w,Math.round((x-offsetX-rect.left)/rect.width*g.w))),ty=Math.max(0,Math.min(g.h-info.h,Math.round((y-offsetY-rect.top)/rect.height*g.h)));this.notice=m.move(id,container,tx,ty)?'Item moved.':'That space is occupied or too small. Choose an empty area.';this.selected=id;redraw();};
 root.querySelectorAll<HTMLElement>('[data-stack],[data-weapon]').forEach(el=>{
 el.onpointerdown=e=>{
  if(e.button!==0)return;e.preventDefault();const startX=e.clientX,startY=e.clientY,r=el.getBoundingClientRect();
  let ghost:HTMLElement|undefined;const offsetX=e.clientX-r.left,offsetY=e.clientY-r.top;
  const cleanup=()=>{ghost?.remove();this.dragging=false;window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);window.removeEventListener('pointercancel',cancel);window.removeEventListener('blur',cancel);};
  const move=(event:PointerEvent)=>{if(event.pointerId!==e.pointerId)return;
   if(!ghost&&Math.hypot(event.clientX-startX,event.clientY-startY)>5){ghost=el.cloneNode(true) as HTMLElement;ghost.removeAttribute('data-stack');ghost.classList.add('gear-drag-ghost');Object.assign(ghost.style,{width:r.width+'px',height:r.height+'px'});document.body.append(ghost);this.dragging=true;}
   if(ghost){ghost.style.left=event.clientX-offsetX+'px';ghost.style.top=event.clientY-offsetY+'px';}
  };
  const end=(event:PointerEvent)=>{if(event.pointerId!==e.pointerId)return;const dragged=!!ghost;cleanup();
   if(dragged)drop(el.dataset.stack||'',event.clientX,event.clientY,el.dataset.weapon,offsetX,offsetY);
   else if(el.dataset.stack){this.selected=el.dataset.stack;this.notice=ITEM_INFO[m.stacks.find(a=>a.id===this.selected)!.kind].desc;redraw();}
   else if(el.dataset.weapon){s.equip(el.dataset.weapon as 'bat'|'rifle',true);redraw();}
  };
  const cancel=()=>cleanup();window.addEventListener('pointermove',move);window.addEventListener('pointerup',end);window.addEventListener('pointercancel',cancel);window.addEventListener('blur',cancel);
 };

 el.ondblclick=()=>{if(el.dataset.stack){this.selected=el.dataset.stack;use();}};
 el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();if(el.dataset.stack){this.selected=el.dataset.stack;this.notice=ITEM_INFO[m.stacks.find(a=>a.id===this.selected)!.kind].desc;redraw();}else{s.equip(el.dataset.weapon as 'bat'|'rifle',true);redraw();}}};});
 root.querySelectorAll<HTMLButtonElement>('[data-cell]').forEach(cell=>cell.onclick=()=>{if(!this.selected)return;this.notice=m.move(this.selected,cell.dataset.cell as Container,Number(cell.dataset.x),Number(cell.dataset.y))?'Item moved.':'That space is occupied or too small.';redraw();});
 }
}
