import {Inventory,ITEM_INFO,GRIDS,type Container} from './inventory';
import type {Simulation} from './sim';
export class InventoryScreen{
 model:Inventory;selected='';notice='Drag items to arrange your gear. Select supplies, then choose USE ITEM.';dragging=false;
 constructor(public s:Simulation,public icon:(name:string)=>string){this.model=new Inventory(s);}
 art(name:string){if(name==='rifle')return '<svg viewBox="0 0 160 65"><path fill="#80704d" stroke="#b5a47d" d="m10 36 35-11 13 4-5 10-40 12Z"/><path fill="#3e4c43" stroke="#acb59d" d="M49 26h51v12H49z"/><path stroke="#a8afa0" stroke-width="5" d="M96 29h54"/><path fill="#29372f" stroke="#869781" d="m65 36 13 1-2 17-11-1Z"/><path stroke="#d0c7a2" stroke-width="3" d="M57 21h30"/></svg>';if(name==='bat')return '<svg viewBox="0 0 160 65"><path d="M19 42 69 31 133 17" stroke="#c2a67a" stroke-width="11" stroke-linecap="round"/><path d="m16 43 43-10" stroke="#776247" stroke-width="5"/><path d="m14 39 3 9" stroke="#b9a079" stroke-width="4"/></svg>';if(name==='water')return '<svg viewBox="0 0 50 95"><path fill="#648c8290" stroke="#adcbc0" d="M17 15h16v9l6 10v47q0 6-6 6H17q-6 0-6-6V34l6-10Z"/><path fill="#a7b9ab" d="M17 8h16v10H17z"/><path fill="#d1ceae" d="M12 43h26v23H12z"/><path stroke="#718c7c" d="M18 49h14m-14 5h14m-11 5h8"/></svg>';if(name==='food')return '<svg viewBox="0 0 65 70"><path fill="#798372" stroke="#c2c6a9" d="M13 15h39v43q-19 9-39 0Z"/><path fill="#a98c61" d="M14 26h37v24H14z"/><ellipse cx="32" cy="15" rx="19" ry="6" fill="#b0b49c"/><path stroke="#e5d7a5" d="M20 33h24m-24 6h24m-20 6h16"/></svg>';if(name==='ammo')return '<svg viewBox="0 0 80 60" fill="none"><path fill="#9b8a55" stroke="#d5c38c" d="M15 44V19l4-9 4 9v25Zm13 0V19l4-9 4 9v25Zm13 0V19l4-9 4 9v25Zm13 0V19l4-9 4 9v25Z"/><path fill="#5a6348" stroke="#a5ab81" d="M10 32h55v20H10z"/><path stroke="#c8c4a1" d="M18 41h39"/></svg>';return this.icon(name);}
 render(root:HTMLElement,close:()=>void){this.model.sync();const m=this.model,s=this.s;const selected=m.stacks.find(a=>a.id===this.selected);
 const grid=(name:Container)=>{const g=GRIDS[name];return `<div class="gear-grid" data-grid="${name}" style="--cols:${g.w};--rows:${g.h}" role="group" aria-label="${name} storage">${Array.from({length:g.w*g.h},(_,i)=>`<button class="gear-cell" style="grid-column:${i%g.w+1};grid-row:${Math.floor(i/g.w)+1}" data-cell="${name}" data-x="${i%g.w}" data-y="${Math.floor(i/g.w)}" aria-label="${name} column ${i%g.w+1} row ${Math.floor(i/g.w)+1}"></button>`).join('')}${m.stacks.filter(a=>a.container===name).map(a=>{const info=ITEM_INFO[a.kind];return `<button class="gear-item ${a.kind.toLowerCase()} ${a.id===this.selected?'selected':''}" data-stack="${a.id}" style="grid-column:${a.x+1}/span ${info.w};grid-row:${a.y+1}/span ${info.h}" aria-label="${info.name}, ${m.quantity(a)}, ${name}"><span>${info.name}</span>${this.art(info.icon)}<b>×${m.quantity(a)}</b></button>`;}).join('')}</div>`;};
 const weapon=(slot:'hands'|'back')=>{const type=slot==='hands'?s.weapon:s.weapon==='bat'?'rifle':'bat';return `<div class="weapon-slot" data-slot="${slot}" role="group" aria-label="${slot==='hands'?'In hands':'On back'} weapon slot"><span class="gear-label">${slot==='hands'?'IN HANDS':'ON BACK'} <small>${slot==='hands'?'ACTIVE':'SLUNG'}</small></span><button class="equipped-weapon" data-weapon="${type}" aria-label="${type==='rifle'?'Carbine':'Wooden bat'} ${slot==='hands'?'in hands':'on back'}">${this.art(type)}<strong>${type==='rifle'?'M6 · Carbine':'Wooden bat'}</strong><b>${type==='rifle'?s.ammo+' / 6':'100%'}</b></button></div>`;};
 root.innerHTML=`<section class="gear-screen" role="dialog" aria-modal="true" aria-label="Inventory management"><header class="gear-header"><div class="gear-brand">ASH COUNTY <span>/ SURVIVOR</span></div><span class="gear-tab">${this.icon('bag')} GEAR</span><span class="gear-paused">● WORLD PAUSED</span><button id="gear-close">BACK <kbd>I / ESC</kbd> ×</button></header><div class="gear-body"><section class="equipment-column"><div class="gear-section-title">EQUIPMENT <span>01 / ALEX MORGAN</span></div><div class="equipment-body"><svg class="body-outline" viewBox="0 0 200 320"><g fill="#77847122" stroke="#a7b39825"><ellipse cx="100" cy="36" rx="23" ry="29"/><path d="m77 62-28 15-27 108 16 5 38-85-9 100 13 99h17l3-87 9 87h17l8-99-8-100 34 85 17-5-28-108-25-15Z"/></g></svg><div class="empty-gear"><span>HEADWEAR</span><i>—</i><small>No head protection</small></div><div class="empty-gear"><span>BODY ARMOR</span><i>—</i><small>No armor equipped</small></div>${weapon('hands')}${weapon('back')}<div class="worn-pack">${this.icon('bag')}<div>CANVAS BACKPACK<small>30 storage cells · Equipped</small></div></div></div><div class="gear-vitals"><span>${this.icon('heart')} ${Math.ceil(s.player.hp)}<small>HEALTH</small></span><span>${this.icon('water')} ${Math.ceil(s.player.thirst)}<small>HYDRATION</small></span><span>${m.weight.toFixed(1)}<small>KG CARRIED</small></span></div></section><section class="carry-column"><div class="gear-section-title">POCKETS <span>QUICK ACCESS</span></div>${grid('pockets')}<div class="gear-section-title backpack-title">BACKPACK <span>CANVAS · 6 × 5</span></div>${grid('backpack')}<div class="gear-tip">${this.icon('compass')} Keep essentials close.<br><span>Drag a weapon between IN HANDS and ON BACK to equip it.</span></div></section><section class="stash-column"><div class="gear-section-title">FIELD STASH <span>8 × 7</span></div>${grid('stash')}<div class="stash-note">Supplies stored here are unavailable to your hotbar.<br>Your stash stays organized for this survival session.</div></section></div><footer class="gear-footer"><div class="item-detail"><strong>${selected?ITEM_INFO[selected.kind].name:'YOUR GEAR. YOUR WAY.'}</strong><span id="gear-notice">${this.notice}</span></div><div class="gear-actions"><button id="gear-use" ${!selected||selected.container==='stash'||selected.kind==='Ammo'?'disabled':''}>USE ITEM</button><button id="gear-transfer" ${!selected?'disabled':''}>${selected?.container==='stash'?'TAKE':'STORE'} ITEM ⇄</button><button id="gear-clear" ${!selected?'disabled':''}>CANCEL</button></div><small>DRAG TO MOVE · CLICK ITEM + CELL TO PLACE</small></footer></section>`;
 root.querySelector<HTMLButtonElement>('#gear-close')!.onclick=close;
 const redraw=()=>this.render(root,close);const message=(text:string)=>{this.notice=text;root.querySelector('#gear-notice')!.textContent=text;};
 root.querySelector<HTMLButtonElement>('#gear-clear')!.onclick=()=>{this.selected='';redraw();};
 const use=()=>{const a=m.stacks.find(a=>a.id===this.selected);if(a&&a.container!=='stash'&&a.kind!=='Ammo'){s.use(a.kind);this.notice=s.message;m.sync();redraw();}};
 root.querySelector<HTMLButtonElement>('#gear-use')!.onclick=use;
 root.querySelector<HTMLButtonElement>('#gear-transfer')!.onclick=()=>{if(m.transfer(this.selected)){this.selected='';this.notice='Item transferred.';}else this.notice='No room in the destination.';redraw();};
 const drop=(id:string,x:number,y:number,weaponType?:string)=>{const el=document.elementFromPoint(x,y) as HTMLElement|null;if(weaponType){const slot=el?.closest<HTMLElement>('[data-slot]');if(slot){s.equip(slot.dataset.slot==='hands'?weaponType as 'bat'|'rifle':weaponType==='bat'?'rifle':'bat',true);this.notice='Weapon equipped.';}else this.notice='Weapons belong in IN HANDS or ON BACK.';redraw();return;}
 const item=el?.closest<HTMLElement>('[data-stack]');const target=item?m.stacks.find(a=>a.id===item.dataset.stack):null;const board=el?.closest<HTMLElement>('[data-grid]');if(!board){message('Drop inside a storage grid.');return;}const rect=board.getBoundingClientRect(),container=board.dataset.grid as Container,g=GRIDS[container];const tx=target?.x??Math.floor((x-rect.left)/rect.width*g.w),ty=target?.y??Math.floor((y-rect.top)/rect.height*g.h);this.notice=m.move(id,container,tx,ty)?'Item moved.':'That space is occupied or too small. Drop onto a matching stack to merge.';this.selected=id;redraw();};
 root.querySelectorAll<HTMLElement>('[data-stack],[data-weapon]').forEach(el=>{
 el.onpointerdown=e=>{if(e.button!==0)return;const startX=e.clientX,startY=e.clientY;let ghost:HTMLElement|undefined;el.setPointerCapture(e.pointerId);el.onpointermove=move=>{if(!ghost&&Math.hypot(move.clientX-startX,move.clientY-startY)>5){ghost=el.cloneNode(true) as HTMLElement;const r=el.getBoundingClientRect();ghost.classList.add('gear-drag-ghost');Object.assign(ghost.style,{width:r.width+'px',height:r.height+'px'});document.body.append(ghost);this.dragging=true;}if(ghost){ghost.style.left=move.clientX+10+'px';ghost.style.top=move.clientY+10+'px';}};el.onpointerup=up=>{el.onpointermove=null;if(ghost){ghost.remove();this.dragging=false;drop(el.dataset.stack||'',up.clientX,up.clientY,el.dataset.weapon);}else if(el.dataset.stack){this.selected=el.dataset.stack;this.notice=ITEM_INFO[m.stacks.find(a=>a.id===this.selected)!.kind].desc;redraw();}else if(el.dataset.weapon){s.equip(el.dataset.weapon as 'bat'|'rifle',true);redraw();}};el.onpointercancel=()=>{ghost?.remove();this.dragging=false;el.onpointermove=null;};};
 el.ondblclick=()=>{if(el.dataset.stack){this.selected=el.dataset.stack;use();}};
 el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();if(el.dataset.stack){this.selected=el.dataset.stack;this.notice=ITEM_INFO[m.stacks.find(a=>a.id===this.selected)!.kind].desc;redraw();}else{s.equip(el.dataset.weapon as 'bat'|'rifle',true);redraw();}}};});
 root.querySelectorAll<HTMLButtonElement>('[data-cell]').forEach(cell=>cell.onclick=()=>{if(!this.selected)return;this.notice=m.move(this.selected,cell.dataset.cell as Container,Number(cell.dataset.x),Number(cell.dataset.y))?'Item moved.':'That space is occupied or too small.';redraw();});
 }
}
