import {CHUNK_SIZE,type Region} from './world';
import type {LootCrate} from './loot';
import {LootPanel} from './loot-panel';
import Phaser from 'phaser';
import './style.css';
import {Simulation,ATTACK_DURATION,type House,type Zombie} from './sim';
import * as Art from './art';
import {UI} from './ui';
async function boot(){
const loading=document.createElement('div');loading.className='asset-loading';loading.textContent='ASH COUNTY · Loading world artwork…';document.body.append(loading);
await Art.loadSprites();loading.remove();
const simulation=new Simulation();
let audioContext:AudioContext|undefined,gain:GainNode|undefined;
function sound(){if(!audioContext){audioContext=new AudioContext();gain=audioContext.createGain();gain.gain.value=.04;gain.connect(audioContext.destination);const buffer=audioContext.createBuffer(1,audioContext.sampleRate*4,audioContext.sampleRate);const channel=buffer.getChannelData(0);let last=0;for(let i=0;i<channel.length;i++){last=(last+Math.random()*.04-.02)/1.02;channel[i]=last*4;}const source=audioContext.createBufferSource();source.buffer=buffer;source.loop=true;const filter=audioContext.createBiquadFilter();filter.type='lowpass';filter.frequency.value=500;source.connect(filter);filter.connect(gain);source.start();}gain!.gain.setTargetAtTime(ui.muted?0:.15,audioContext.currentTime,.3);void audioContext.resume();}
const ui=new UI(simulation,()=>location.reload(),sound);
let effectsGain:GainNode|undefined,engineTimer=0,stepDistance=0,lastDistance=0,lastShot=0,lastSwing=0,zombieTimer=0;
function sfx(kind:'step'|'run'|'engine'|'zombie'|'shot'|'bat'){
 if(ui.muted)return;sound();if(!audioContext)return;if(!effectsGain){effectsGain=audioContext.createGain();effectsGain.gain.value=.22;effectsGain.connect(audioContext.destination);}
 const now=audioContext.currentTime,o=audioContext.createOscillator(),g=audioContext.createGain();o.connect(g);g.connect(effectsGain);
 const settings={step:[150,.055,'triangle',.07],run:[115,.06,'triangle',.09],engine:[72,.16,'sawtooth',.12],zombie:[185,.28,'sine',.09],shot:[125,.11,'square',.18],bat:[82,.16,'triangle',.16]}[kind] as [number,number,OscillatorType,number];
 o.type=settings[2];o.frequency.setValueAtTime(settings[0],now);o.frequency.exponentialRampToValueAtTime(Math.max(35,settings[0]*.55),now+settings[1]);g.gain.setValueAtTime(settings[3],now);g.gain.exponentialRampToValueAtTime(.001,now+settings[1]);o.start(now);o.stop(now+settings[1]);
}
const lootPanel=new LootPanel(simulation,name=>ui.inventory.art(name));
const mobile={x:0,y:0};
document.querySelectorAll<HTMLButtonElement>('[data-move]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);const d=b.dataset.move;mobile.x=d==='left'?-1:d==='right'?1:0;mobile.y=d==='up'?-1:d==='down'?1:0;};b.onpointerup=b.onpointercancel=()=>{mobile.x=mobile.y=0;};});
class World extends Phaser.Scene {
 muzzleSprite!:Phaser.GameObjects.Image;impactSprite!:Phaser.GameObjects.Image;playerSprite!:Phaser.GameObjects.Image;vehicleSprites=new Map<string,Phaser.GameObjects.Image>(); zombieSprites=new Map<Zombie,Phaser.GameObjects.Image>();crateSprites=new Map<LootCrate,Phaser.GameObjects.Image>();buildingSprites=new Map<House,{sprite:Phaser.GameObjects.Image;key:string}>();regions=new Map<string,{objects:Phaser.GameObjects.GameObject[];textures:string[];region:Region}>();firing=false; trees:Phaser.GameObjects.Image[]=[];keys!:Record<string,Phaser.Input.Keyboard.Key>;ring!:Phaser.GameObjects.Graphics; fx!:Phaser.GameObjects.Graphics; camReady=false;hudTick=0;survivorCanvas=Art.canvas(96,112);
 constructor(){super('neighborhood');}
 create(){const register=(key:string,c:HTMLCanvasElement)=>this.textures.addCanvas(key,c);for(let i=0;i<32;i++)register('drivable-'+i,Art.driveCar(i/32*Math.PI*2));for(const kind of ['bench','grave','hay','pump','sign','barrel'])register('prop-'+kind,Art.scenery(kind));register('crate',Art.storageCrate());register('crate-empty',Art.storageCrate(true));for(let i=0;i<3;i++)register('tree-'+i,Art.tree(i));for(const action of ['idle','walk','attack','hurt'] as const)for(let i=0;i<16;i++){register(`zombie-${action}-${i}`,Art.undead(action,i));register(`zombie-${action}-${i}-back`,Art.undead(action,i,true));}register('survivor',Art.survivor('idle',0,false,'bat',false,0,this.survivorCanvas));register('car-green',Art.car('#7c8978'));register('car-red',Art.car('#977766'));register('car-blue',Art.car('#748985'));register('fence',Art.fence());register('lamp',Art.lamp());register('mailbox',Art.mailbox());
 for(let i=0;i<8;i++)register('effect-'+i,Art.effect(i));this.muzzleSprite=this.add.image(0,0,'effect-0').setDepth(1e12).setVisible(false);this.impactSprite=this.add.image(0,0,'effect-4').setDepth(1e12).setVisible(false);this.syncRegions();
 this.ring=this.add.graphics();this.fx=this.add.graphics().setDepth(1e12);this.playerSprite=this.add.image(0,0,'survivor').setOrigin(.5,100/112);
 this.keys=this.input.keyboard!.addKeys('W,A,S,D,UP,LEFT,DOWN,RIGHT,SHIFT,C,SPACE,E,I,M,J,ESC,TWO,THREE,FOUR,FIVE,ONE') as Record<string,Phaser.Input.Keyboard.Key>;
 this.input.keyboard!.on('keydown',(event:KeyboardEvent)=>{if(event.repeat)return;const k=event.key.toLowerCase();if(k==='escape'){this.firing=false;if(lootPanel.crate){lootPanel.close();return;}ui.toggle(ui.panel||'pause');return;}if(['i','m','j'].includes(k)){this.firing=false;ui.toggle({i:'inventory',m:'map',j:'journal'}[k]!);return;}if(ui.panel)return;if(k==='f'){this.firing=false;simulation.toggleVehicle();}if(k==='e')simulation.interact();if(k===' '){if(simulation.driving)simulation.vehicle.speed=0;else simulation.attack();}if(k==='1')simulation.equip('bat');if(k==='6')simulation.equip('rifle');if(k==='q')simulation.equip(simulation.weapon==='bat'?'rifle':'bat');if(k==='r')simulation.reload();if(k==='2')simulation.use('Bandage');if(k==='3')simulation.use('Water');if(k==='4')simulation.use('Beans');if(k==='5')simulation.use('Plank');});
 this.input.mouse!.disableContextMenu();this.input.on('pointerdown',(pointer:Phaser.Input.Pointer,over:Phaser.GameObjects.GameObject[])=>{if(!ui.panel&&pointer.leftButtonDown()){const target=over.find(o=>o.getData('crateId'));if(target){this.firing=false;const crate=simulation.crates.find(c=>c.id===target.getData('crateId'));if(crate)lootPanel.open(crate);return;}this.firing=simulation.weapon==='rifle';if(this.firing)this.facePointer(pointer);simulation.attack();}});this.input.on('pointerup',(p:Phaser.Input.Pointer)=>{if(!p.leftButtonDown())this.firing=false;});window.addEventListener('pointerup',(e:PointerEvent)=>{if(e.button===0)this.firing=false;});document.querySelector('#ui')!.addEventListener('pointerdown',()=>{this.firing=false;},true);this.input.on('wheel',(_p:unknown,_o:unknown,_x:number,dy:number)=>{this.cameras.main.setZoom(Phaser.Math.Clamp(this.cameras.main.zoom-dy*.001,.45,1.65));});
 this.cameras.main.setZoom(window.innerWidth<760?1:1.1);this.cameras.main.setBackgroundColor('#4e5b40');window.addEventListener('blur',()=>{this.firing=false;if(!ui.panel&&!simulation.dead&&!simulation.won)ui.toggle('pause');});this.game.events.on(Phaser.Core.Events.HIDDEN,()=>{if(!ui.panel&&!simulation.dead&&!simulation.won)ui.toggle('pause');});
 }
 syncRegions(){const keys=new Set(simulation.world.active.map(r=>r.key));for(const [key,view]of this.regions){if(keys.has(key))continue;for(const object of view.objects)object.destroy();for(const texture of view.textures)this.textures.remove(texture);for(const h of view.region.houses)this.buildingSprites.delete(h);for(const c of view.region.crates)this.crateSprites.delete(c);this.regions.delete(key);}this.trees=this.trees.filter(t=>t.active);
 for(const region of simulation.world.active){if(this.regions.has(region.key))continue;const objects:Phaser.GameObjects.GameObject[]=[],textures:string[]=[];const ox=region.cx*CHUNK_SIZE,oy=region.cy*CHUNK_SIZE,offset=Art.iso(ox,oy),zero=Art.iso(0,0);const register=(key:string,c:HTMLCanvasElement)=>{this.textures.addCanvas(key,c);textures.push(key);};const groundKey='ground:'+region.key;register(groundKey,Art.ground(region.houses.map(h=>({...h,x:h.x-ox,y:h.y-oy})),region.seed,region.patches.map(p=>({...p,x:p.x-ox,y:p.y-oy}))));objects.push(this.add.image(offset.x-zero.x,offset.y-zero.y,groundKey).setOrigin(0).setScale(2).setDepth(-1e9));
 region.houses.forEach((h,i)=>{const key=`house:${region.key}:${i}`;register(key,Art.house(h));register(key+'-open',Art.house({...h,door:true}));register(key+'-inside',Art.house(h,true));const p=Art.iso(h.x,h.y);const sprite=this.add.image(p.x-218,p.y-93,key).setOrigin(0).setDepth(p.y+(h.w+h.d)*16-2);objects.push(sprite);this.buildingSprites.set(h,{sprite,key});const q=Art.iso(h.x+.1,h.y+h.d+.7);objects.push(this.add.image(q.x,q.y,'mailbox').setOrigin(.52,.9).setDepth(q.y));});
 region.trees.forEach((tree,i)=>{const p=Art.iso(tree.x,tree.y);const t=this.add.image(p.x,p.y,'tree-'+tree.variant).setOrigin(.5,.9).setDepth(p.y).setScale(.75+(i%5)*.09);objects.push(t);this.trees.push(t);});
 region.props.forEach(prop=>{const p=Art.iso(prop.x,prop.y);objects.push(this.add.image(p.x,p.y,'prop-'+prop.kind).setOrigin(.5,.88).setDepth(p.y));});
 region.vehicles.forEach(vehicle=>{const p=Art.iso(vehicle.x,vehicle.y),sprite=this.add.image(p.x,p.y,'drivable-'+((Math.round(vehicle.angle/(Math.PI*2)*32)%32+32)%32)).setOrigin(.5,96/160).setDepth(p.y).setData('vehicleId',vehicle.id);objects.push(sprite);this.vehicleSprites.set(vehicle.id,sprite);});
 region.crates.forEach(crate=>{const p=Art.iso(crate.x,crate.y);const sprite=this.add.image(p.x,p.y,'crate').setOrigin(.5,70/78).setDepth(p.y).setData('crateId',crate.id).setInteractive({useHandCursor:true});sprite.on('pointerover',()=>sprite.setTint(0xe5d6a3));sprite.on('pointerout',()=>sprite.clearTint());objects.push(sprite);this.crateSprites.set(crate,sprite);});this.regions.set(region.key,{objects,textures,region});}}
 facePointer(pointer:Phaser.Input.Pointer){const world=this.cameras.main.getWorldPoint(pointer.x,pointer.y);const p=simulation.player,q=Art.iso(p.x,p.y);const dx=world.x-q.x,dy=world.y-(q.y-48);if(Math.hypot(dx,dy)>8)p.angle=Math.atan2(dy/32-dx/64,dy/32+dx/64);}
 update(_time:number,delta:number){if(!this.keys)return;const k=this.keys;simulation.player.aiming=!simulation.driving&&simulation.weapon==='rifle'&&!ui.panel&&!simulation.dead&&!simulation.won&&this.input.activePointer.rightButtonDown();if(simulation.player.aiming)this.facePointer(this.input.activePointer);const sx=Number(k.D.isDown||k.RIGHT.isDown)-Number(k.A.isDown||k.LEFT.isDown)+mobile.x,sy=Number(k.S.isDown||k.DOWN.isDown)-Number(k.W.isDown||k.UP.isDown)+mobile.y;simulation.update(delta/1000,{x:sx+sy,y:sy-sx,run:k.SHIFT.isDown,sneak:k.C.isDown});if(this.firing&&this.input.activePointer.leftButtonDown()&&!ui.panel&&!simulation.paused){const hit=document.elementFromPoint(this.input.activePointer.x,this.input.activePointer.y);if(hit===this.game.canvas&&simulation.weapon==='rifle'){this.facePointer(this.input.activePointer);simulation.attack();}else this.firing=false;}const p=simulation.player,q=Art.iso(p.x,p.y);const action:Art.SurvivorAction=simulation.damageTime>0?'hurt':simulation.attackTime>0&&simulation.weapon==='bat'?'attack':p.moving?(p.sneaking?'sneak':p.running?'run':'walk'):'idle';const frame=action==='hurt'?Math.min(7,Math.floor((1-simulation.damageTime/.3)*8)):action==='attack'?Math.min(7,Math.floor((1-simulation.attackTime/ATTACK_DURATION)*8)):p.moving?(p.gait*8)%8:(simulation.elapsed*3)%8;const back=Math.cos(p.angle)+Math.sin(p.angle)<0;const flip=Math.cos(p.angle)-Math.sin(p.angle)<0;const screenAngle=Math.atan2((Math.cos(p.angle)+Math.sin(p.angle))*16,Math.abs((Math.cos(p.angle)-Math.sin(p.angle))*32));Art.survivor(action,frame,back,simulation.weapon,p.aiming,screenAngle,this.survivorCanvas);(this.textures.get('survivor') as Phaser.Textures.CanvasTexture).refresh();
 for(const vehicle of simulation.vehicles){const sprite=this.vehicleSprites.get(vehicle.id);if(!sprite)continue;const at=Art.iso(vehicle.x,vehicle.y);sprite.setPosition(at.x,at.y).setDepth(at.y).setTexture('drivable-'+((Math.round(vehicle.angle/(Math.PI*2)*32)%32+32)%32));}this.playerSprite.setVisible(!simulation.driving);this.ring.setVisible(!simulation.driving);this.playerSprite.setPosition(q.x,q.y).setDepth(q.y+.2).setFlipX(flip).setAlpha(p.hp<=0?.4:1);this.playerSprite.setTint(simulation.damageTime>0?0xff9977:0xffffff);
 this.ring.clear().setDepth(q.y-.2);this.ring.lineStyle(1,0xd9d5a0,.55);this.ring.strokeEllipse(q.x,q.y+1,28,13);this.ring.fillStyle(0xc1c397,.7);this.ring.fillCircle(q.x,q.y+1,2);
 this.muzzleSprite.setVisible(false);this.impactSprite.setVisible(false);const hitZombie=simulation.zombies.find(z=>z.hit>0&&z.hp>0);if(hitZombie){const hitAt=Art.iso(hitZombie.x,hitZombie.y);this.impactSprite.setPosition(hitAt.x,hitAt.y-35).setTexture('effect-'+(4+Math.min(3,Math.floor((1-hitZombie.hit/.25)*4)))).setVisible(true);}
 this.fx.clear();if(simulation.shotTime>0&&simulation.shotEnd){const end=Art.iso(simulation.shotEnd.x,simulation.shotEnd.y);this.fx.lineStyle(2,0xf4d68d,simulation.shotTime/.12);this.fx.lineBetween(q.x,q.y-48,end.x,end.y-48);const muzzleAngle=Math.atan2(end.y-q.y,end.x-q.x);this.muzzleSprite.setPosition(q.x+Math.cos(muzzleAngle)*27,q.y-48+Math.sin(muzzleAngle)*27).setRotation(muzzleAngle).setTexture('effect-'+Math.min(3,Math.floor((1-simulation.shotTime/.12)*4))).setVisible(true);}if(p.aiming){const pointer=this.input.activePointer,at=this.cameras.main.getWorldPoint(pointer.x,pointer.y);this.fx.lineStyle(1,0xe1d7a5,.8);this.fx.strokeCircle(at.x,at.y,7);this.fx.lineBetween(at.x-12,at.y,at.x-4,at.y);this.fx.lineBetween(at.x+4,at.y,at.x+12,at.y);}if(simulation.attackTime>0){const a=1-simulation.attackTime/ATTACK_DURATION;this.fx.lineStyle(3,0xe3d7a9,(1-a)*.8);this.fx.beginPath();this.fx.arc(q.x,q.y-24,35,-1+a*2,1.3+a*2);this.fx.strokePath();}
 const alive=new Set(simulation.zombies.filter(z=>z.hp>0&&Math.hypot(z.x-p.x,z.y-p.y)<38));for(const [z,sprite]of this.zombieSprites)if(!alive.has(z)){sprite.destroy();this.zombieSprites.delete(z);}for(const z of alive){let sprite=this.zombieSprites.get(z);if(!sprite){sprite=this.add.image(0,0,'zombie-idle-0').setOrigin(.5,100/112);this.zombieSprites.set(z,sprite);}const at=Art.iso(z.x,z.y);const state=z.hit>0?'hurt':z.cooldown>1?'attack':z.moving?'walk':'idle';const phase=state==='hurt'?Math.floor((1-z.hit/.25)*15):state==='attack'?Math.floor((1.4-z.cooldown)*35):Math.floor((z.moving?(z.gait||0):simulation.elapsed*.25)*16);sprite.setPosition(at.x,at.y).setDepth(at.y).setTexture(`zombie-${state}-${Math.max(0,phase)%16}${Math.cos(z.angle||0)+Math.sin(z.angle||0)<0?'-back':''}`).setFlipX(Math.cos(z.angle||0)-Math.sin(z.angle||0)<0);sprite.setTint(z.hit>0?0xd59776:0xffffff);}
 for(const [h,view]of this.buildingSprites){const inside=simulation.inside(p)===h;view.sprite.setTexture(view.key+(inside?'-inside':h.door?'-open':'')).setDepth(inside?Art.iso(h.x,h.y).y-5:Art.iso(h.x,h.y).y+(h.w+h.d)*16-2);}
 for(const [crate,sprite]of this.crateSprites){const inside=simulation.inside(crate);sprite.setVisible(!inside||simulation.inside(p)===inside).setTexture(crate.items.some(item=>item.quantity>0)?'crate':'crate-empty');}
 this.trees.forEach(t=>t.setAlpha(Math.abs(t.x-q.x)<75&&t.y>q.y&&t.y-q.y<180?.35:1));
 const camera=this.cameras.main;if(!this.camReady){camera.centerOn(q.x,q.y-35);this.camReady=true;}else{const mid=camera.midPoint;camera.centerOn(Phaser.Math.Linear(mid.x,q.x,1-Math.exp(-delta/85)),Phaser.Math.Linear(mid.y,q.y-35,1-Math.exp(-delta/85)));}
 this.hudTick+=delta;if(this.hudTick>100){this.syncRegions();ui.update();lootPanel.update();this.hudTick=0;}
 }
}
const game=new Phaser.Game({type:Phaser.AUTO,parent:'game',width:window.innerWidth,height:window.innerHeight,backgroundColor:'#45533b',render:{antialias:false,pixelArt:true},scale:{mode:Phaser.Scale.RESIZE,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[World],audio:{noAudio:true}});
// Read-only state snapshot for accessibility and automated playtesting.
Object.assign(window,{render_game_to_text:()=>JSON.stringify({coordinates:'World tile coordinates, +x southeast, +y southwest',player:simulation.player,vehicle:simulation.vehicle,driving:simulation.driving,inventory:simulation.bag,crates:simulation.crates,openCrate:lootPanel.crate?.id,weapon:simulation.weapon,ammo:simulation.ammo,reserve:simulation.reserve,kills:simulation.kills,searched:simulation.searched,paused:simulation.paused,dead:simulation.dead,won:simulation.won,nearHouse:simulation.nearHouse()?.name,inside:simulation.inside(simulation.player)?.name,zombies:simulation.zombies.map(z=>({x:z.x,y:z.y,hp:z.hp,alert:z.alert})),regions:simulation.world.active.map(r=>r.key),visitedRegions:simulation.world.cache.size,houses:simulation.houses.map(h=>({name:h.name,x:h.x,y:h.y,door:h.door,searched:h.searched})),elapsed:simulation.elapsed}),game});
window.setInterval(()=>{if(simulation.paused||simulation.dead||simulation.won)return;const p=simulation.player,deltaDistance=Math.max(0,p.distance-lastDistance);lastDistance=p.distance;stepDistance+=deltaDistance;if(!simulation.driving&&p.moving&&stepDistance>=(p.running?.62:p.sneaking?1.08:.82)){sfx(p.running?'run':'step');stepDistance=0;}engineTimer-=.06;if(simulation.driving&&Math.abs(simulation.vehicle.speed)>.25&&engineTimer<=0){sfx('engine');engineTimer=.16;}zombieTimer-=.06;if(zombieTimer<=0&&simulation.zombies.some(z=>z.hp>0&&z.alert)){sfx('zombie');zombieTimer=2.4;}if(simulation.shotTime>lastShot+.02){sfx('shot');}if(simulation.attackTime>lastSwing+.02&&simulation.weapon==='bat'){sfx('bat');}lastShot=simulation.shotTime;lastSwing=simulation.attackTime;},60);

}
void boot().catch(error=>{console.error(error);const loading=document.querySelector('.asset-loading');if(loading)loading.textContent='Artwork could not load. Please refresh to retry.';});
