import type {Simulation} from './sim';
import {LOOT_INFO,type LootCrate} from './loot';
export class LootPanel{
 crate:LootCrate|null=null;root:HTMLDivElement;signature='';
 constructor(public s:Simulation,public art:(name:string)=>string){this.root=document.createElement('div');this.root.className='loot-window';this.root.hidden=true;document.querySelector('#ui')!.append(this.root);}
 open(crate:LootCrate){if(this.s.paused||this.s.dead||this.s.won)return;if(!this.s.canLoot(crate)){this.s.say('Walk closer to the storage crate, then click it.');return;}this.crate=crate;this.signature='';this.render();}
 close(){this.crate=null;this.root.hidden=true;}
 update(){if(!this.crate)return;if(this.s.paused||!this.s.canLoot(this.crate)){this.close();return;}const signature=JSON.stringify(this.crate.items);if(signature!==this.signature)this.render();}
 render(){const crate=this.crate;if(!crate)return;const scroll=this.root.querySelector('.loot-scroll')?.scrollTop||0;this.root.hidden=false;this.signature=JSON.stringify(crate.items);const items=crate.items.filter(i=>i.quantity>0);this.root.innerHTML=`<section aria-label="Container loot"><header class="loot-heading"><div><span class="loot-overline">NEARBY STORAGE</span><h2>${crate.name}</h2></div><button id="loot-close" aria-label="Close loot panel">×</button></header><div class="loot-toolbar"><button id="loot-all" ${items.length?'':'disabled'}>↓ LOOT ALL</button><span>${items.reduce((n,i)=>n+i.quantity,0)} items <i>·</i> ${items.length} stacks</span></div><div class="loot-columns"><span>ITEM</span><span>CATEGORY</span><span>QTY</span><span></span></div><div class="loot-scroll" tabindex="0" aria-label="Scrollable container items">${items.length?items.map(i=>{const info=LOOT_INFO[i.kind];return `<div class="loot-row"><span class="loot-name">${this.art(info.icon)}<span>${info.name}</span></span><span class="loot-category">${info.category}</span><b>${i.quantity}</b><button data-take="${i.id}" aria-label="Take ${info.name}">TAKE</button></div>`;}).join(''):'<div class="loot-empty">Nothing left inside.<small>You’ve searched this container.</small></div>'}</div><footer><span class="live-dot"></span> WORLD LIVE <span>Move away or press Esc to close</span></footer></section>`;
 this.root.querySelector<HTMLButtonElement>('#loot-close')!.onclick=()=>this.close();this.root.querySelector<HTMLButtonElement>('#loot-all')!.onclick=()=>{this.s.loot(crate.id);this.render();};this.root.querySelectorAll<HTMLButtonElement>('[data-take]').forEach(b=>b.onclick=()=>{this.s.loot(crate.id,b.dataset.take);this.render();});this.root.querySelector('.loot-scroll')!.scrollTop=scroll;
 }
}
