import type {Simulation} from './sim';
import {LOOT_INFO,type LootCrate} from './loot';
import {ITEM_INFO} from './inventory';
export class LootPanel{
 crate:LootCrate|null=null;root:HTMLDivElement;signature='';deposit=false;
 constructor(public s:Simulation,public art:(name:string)=>string){this.root=document.createElement('div');this.root.className='loot-window';this.root.hidden=true;document.querySelector('#ui')!.append(this.root);}
 open(crate:LootCrate){if(this.s.paused||this.s.dead||this.s.won)return;if(!this.s.canLoot(crate)){this.s.say('Walk closer to the container, then click it.');return;}this.crate=crate;this.deposit=false;this.signature='';this.render();}
 close(){this.crate=null;this.root.hidden=true;}
 update(){if(!this.crate)return;if(this.s.paused||!this.s.canLoot(this.crate)){this.close();return;}const signature=JSON.stringify([this.crate.items,this.s.bag,this.s.life.ammo]);if(signature!==this.signature)this.render();}
 render(){const crate=this.crate;if(!crate)return;const s=this.s,scroll=this.root.querySelector('.loot-scroll')?.scrollTop||0;this.root.hidden=false;this.signature=JSON.stringify([crate.items,s.bag,s.life.ammo]);
 const items=this.deposit?Object.keys(ITEM_INFO).filter(k=>s.life.quantity(k)>0).map(kind=>({id:kind,kind,quantity:s.life.quantity(kind)})):crate.items.filter(i=>i.quantity>0);
 const stored=crate.items.reduce((n,i)=>n+(ITEM_INFO[i.kind]?.weight||.2)*i.quantity,0);
 this.root.innerHTML=`<section aria-label="Container storage"><header class="loot-heading"><div><span class="loot-overline">NEARBY STORAGE</span><h2>${crate.name}</h2></div><button id="loot-close" aria-label="Close storage">×</button></header><div class="loot-toolbar"><button id="loot-tab" aria-pressed="${!this.deposit}">TAKE</button><button id="deposit-tab" aria-pressed="${this.deposit}">DEPOSIT</button><button id="loot-all" ${items.length?'':'disabled'}>${this.deposit?'STORE':'TAKE'} ALL</button></div><div class="storage-weight">Container ${stored.toFixed(1)} / ${crate.capacity||100} kg · You ${s.inventory.weight.toFixed(1)} / 42 kg${crate.fridge?' · '+(s.life.powered(crate)?'REFRIGERATED':'NO POWER'):''}</div><div class="loot-columns"><span>ITEM</span><span>CATEGORY</span><span>QTY</span><span></span></div><div class="loot-scroll" tabindex="0" aria-label="Scrollable storage items">${items.length?items.map(i=>{const info=ITEM_INFO[i.kind];return `<div class="loot-row"><span class="loot-name">${this.art(info?.icon||i.kind)}<span>${info?.name||i.kind}</span></span><span class="loot-category">${LOOT_INFO[i.kind as keyof typeof LOOT_INFO]?.category||'Furniture'}</span><b>${i.quantity}</b><button data-transfer="${i.kind}">${this.deposit?'STORE':'TAKE'}</button></div>`;}).join(''):'<div class="loot-empty">'+(this.deposit?'Nothing to deposit.':'Empty container. Store supplies here for later.')+'</div>'}</div><footer><span class="live-dot"></span> WORLD LIVE <span>Shift-click transfers a full stack</span></footer></section>`;
 this.root.querySelector<HTMLButtonElement>('#loot-close')!.onclick=()=>this.close();this.root.querySelector<HTMLButtonElement>('#loot-tab')!.onclick=()=>{this.deposit=false;this.render();};this.root.querySelector<HTMLButtonElement>('#deposit-tab')!.onclick=()=>{this.deposit=true;this.render();};
 this.root.querySelector<HTMLButtonElement>('#loot-all')!.onclick=()=>{let moved=0;for(const i of items)moved+=s.life.transfer(crate,i.kind,this.deposit,i.quantity);s.say(moved?`Transferred ${moved} items.`:'No space available.');this.render();};
 this.root.querySelectorAll<HTMLButtonElement>('[data-transfer]').forEach(b=>b.onclick=e=>{const kind=b.dataset.transfer!,n=e.shiftKey?items.find(i=>i.kind===kind)!.quantity:1;s.life.transfer(crate,kind,this.deposit,n);this.render();});this.root.querySelector('.loot-scroll')!.scrollTop=scroll;
 }
}
