import {ProceduralWorld} from './world.js';
import {createCrates,type LootCrate} from './loot.js';
export type Point = { x:number; y:number };
export type House = Point & { w:number; d:number; style?:'home'|'shop'|'warehouse'|'barn';color:string; roof:string; name:string; door:boolean; searched:boolean; loot:string[] };
export type Zombie = Point & { hp:number; phase:number; alert:boolean; cooldown:number; hit:number;gait?:number;moving?:boolean;angle?:number;pushX?:number;pushY?:number };
export const SIZE=46;
export const MOVEMENT_SPEED={walk:2.7,run:4.6,sneak:1.35};
export const ATTACK_DURATION=.38;
export const houses:House[] = [
 {x:12,y:13,w:5,d:5,color:'#96917a',roof:'#555851',name:'14 · Wren Street',loot:['Beans','Water','Bandage']},
 {x:21,y:13,w:5,d:5,color:'#8b9991',roof:'#60544c',name:'16 · Wren Street',loot:['Beans','Plank','Bandage']},
 {x:30,y:13,w:5,d:5,color:'#a49a83',roof:'#515951',name:'18 · Wren Street',loot:['Water','Plank']},
 {x:12,y:27,w:5,d:6,color:'#9a8875',roof:'#666051',name:'13 · Wren Street',loot:['Beans','Water']},
 {x:21,y:27,w:5,d:5,color:'#abb0a0',roof:'#5b514d',name:'15 · Wren Street',loot:['Bandage','Plank','Water']},
 {x:30,y:27,w:5,d:5,color:'#869283',roof:'#595b51',name:'17 · Wren Street',loot:['Beans','Water','Plank']},
 {x:3,y:12,w:5,d:5,color:'#95927f',roof:'#5f534b',name:'10 · Wren Street',loot:['Water','Bandage']},
 {x:39,y:27,w:4,d:5,color:'#a89b84',roof:'#565c52',name:'19 · Wren Street',loot:['Beans','Bandage']},
].map(h=>({...h,door:false,searched:false}));
export class Simulation {
 player={x:23.2,y:23.7,hp:100,stamina:100,hunger:82,thirst:76,angle:1.2,moving:false,sneaking:false,running:false,distance:0,gait:0,exhausted:false,aiming:false};
 world=new ProceduralWorld(houses);
 houses=houses;
 crates=createCrates();
 zombies:Zombie[]=[]; bag:Record<string,number>={Beans:1,Water:1,Bandage:1,Plank:0};
 vehicle={x:25.5,y:23.5,angle:0,speed:0};driving=false;
 weapon:'bat'|'rifle'='bat';ammo=6;reserve=24;shotTime=0;shotEnd:Point|null=null;
 elapsed=0; kills=0; searched=0; attackTime=0; damageTime=0; paused=false; dead=false; won=false; barricaded=false; sound=0; message='Find supplies. Make a home. See another sunrise.'; messageTime=8; attackCooldown=0;
 constructor(){this.refreshWorld();}
 refreshWorld(){this.houses=this.world.active.flatMap(r=>r.houses);this.crates=[...this.world.active].sort((a,b)=>Number(b.key==='0,0')-Number(a.key==='0,0')).flatMap(r=>r.crates);this.zombies=this.world.active.flatMap(r=>r.zombies);}
 streamWorld(){if(this.world.ensure(this.player.x,this.player.y))this.refreshWorld();}
 inside(p:Point){return this.houses.find(h=>p.x>h.x&&p.x<h.x+h.w&&p.y>h.y&&p.y<h.y+h.d);}
 doorPoint(h:House){return {x:h.x+h.w/2,y:h.y+h.d};}
 nearHouse(){return this.houses.find(h=>this.inside(this.player)===h||Math.hypot(this.player.x-this.doorPoint(h).x,this.player.y-this.doorPoint(h).y)<1.8);}
 blocked(x:number,y:number){const radius=.24;if(this.world.active.some(r=>r.patches.some(p=>p.kind==='water'&&x>=p.x&&x<=p.x+p.w&&y>=p.y&&y<=p.y+p.h)))return true;return this.houses.some(h=>{const withinX=x>=h.x-radius&&x<=h.x+h.w+radius,withinY=y>=h.y-radius&&y<=h.y+h.d+radius;if(!withinX||!withinY)return false;const side=Math.abs(x-h.x)<=radius||Math.abs(x-h.x-h.w)<=radius;const rear=Math.abs(y-h.y)<=radius;const front=Math.abs(y-h.y-h.d)<=radius;const opening=h.door&&Math.abs(x-h.x-h.w/2)<.38;return side||rear||(front&&!opening);});}
 move(p:Point,dx:number,dy:number){const steps=Math.max(1,Math.ceil(Math.hypot(dx,dy)/.12));for(let i=0;i<steps;i++){if(!this.blocked(p.x+dx/steps,p.y))p.x+=dx/steps;if(!this.blocked(p.x,p.y+dy/steps))p.y+=dy/steps;}}
 say(m:string){this.message=m;this.messageTime=5;}
 update(dt:number,input:{x:number;y:number;run:boolean;sneak:boolean}){if(this.paused||this.dead||this.won)return;dt=Math.min(dt,.05);this.streamWorld();this.elapsed+=dt;this.shotTime=Math.max(0,this.shotTime-dt);this.messageTime-=dt;this.attackTime=Math.max(0,this.attackTime-dt);this.attackCooldown-=dt;this.damageTime=Math.max(0,this.damageTime-dt);this.sound=Math.max(0,this.sound-dt*3);const p=this.player;p.moving=!!(input.x||input.y);p.sneaking=input.sneak;if(p.stamina<=4)p.exhausted=true;else if(p.stamina>=24)p.exhausted=false;const run=input.run&&!input.sneak&&!p.aiming&&!p.exhausted&&p.moving;const speed=(run?MOVEMENT_SPEED.run:input.sneak?MOVEMENT_SPEED.sneak:MOVEMENT_SPEED.walk)*(p.aiming?.6:1);const oldX=p.x,oldY=p.y;const n=Math.hypot(input.x,input.y)||1;if(this.driving)this.drive(dt,(input.x-input.y)/2,-(input.x+input.y)/2);else this.move(p,input.x/n*speed*dt,input.y/n*speed*dt);const traveled=Math.hypot(p.x-oldX,p.y-oldY);p.distance+=traveled;p.gait+=traveled/(run?1.7:1.35);p.moving=traveled>.0001;p.running=!this.driving&&run&&p.moving;if(p.moving){if(!p.aiming&&!this.driving)p.angle=Math.atan2(input.y,input.x);this.sound=Math.max(this.sound,run?10:input.sneak?1:3);}p.stamina=Math.max(0,Math.min(100,p.stamina+(run&&!this.driving?-14:8)*dt));p.hunger=Math.max(0,p.hunger-dt*.055);p.thirst=Math.max(0,p.thirst-dt*(run?.14:.085));if(p.hunger===0||p.thirst===0)p.hp-=dt*.5;
 for(const z of this.zombies){z.hit=Math.max(0,z.hit-dt);if(z.hp<=0||Math.hypot(z.x-p.x,z.y-p.y)>36)continue;z.cooldown-=dt;const oldX=z.x,oldY=z.y,d=Math.hypot(p.x-z.x,p.y-z.y);z.alert=d<(input.sneak?3:5.5)+this.sound*.3;
 if(z.hit>0){this.move(z,(z.pushX||0)*dt,(z.pushY||0)*dt);z.pushX=(z.pushX||0)*Math.exp(-dt*7);z.pushY=(z.pushY||0)*Math.exp(-dt*7);}else if(z.alert&&d>.55){this.move(z,(p.x-z.x)/d*.82*dt,(p.y-z.y)/d*.82*dt);}else if(!z.alert){this.move(z,Math.cos(this.elapsed*.14+z.phase)*.24*dt,Math.sin(this.elapsed*.12+z.phase)*.24*dt);}
 const traveled=Math.hypot(z.x-oldX,z.y-oldY);z.moving=traveled>.00001;z.gait=(z.gait||0)+traveled/1.1;if(z.moving&&z.hit<=0)z.angle=Math.atan2(z.y-oldY,z.x-oldX);if(this.driving&&d<1.5&&Math.abs(this.vehicle.speed)>3){z.hp=0;this.kills++;continue;}if(!this.driving&&d<.8&&z.cooldown<=0&&z.hit<=0){p.hp-=9;z.cooldown=1.4;this.damageTime=.3;this.say('You were scratched. Create some distance.');}}
 if(p.hp<=0){p.hp=0;this.dead=true;this.say('Every life leaves a trace.');}}
 equip(weapon:'bat'|'rifle',fromInventory=false){if((this.paused&&!fromInventory)||this.dead||this.won)return;this.weapon=weapon;this.player.aiming=false;this.attackTime=0;this.say(weapon==='rifle'?'Carbine equipped · Hold right mouse to aim · Hold left mouse to fire':'Bat equipped · Carbine slung on your back');}
 reload(){if(this.paused||this.dead||this.won||this.weapon!=='rifle'||this.attackCooldown>0)return;const rounds=Math.min(6-this.ammo,this.reserve);if(!rounds){this.say(this.ammo===6?'Magazine is full.':'No spare ammunition.');return;}this.ammo+=rounds;this.reserve-=rounds;this.attackCooldown=.8;this.say('Carbine reloaded.');}
 fire(){if(this.ammo<=0){this.say('Empty · Press R to reload');this.attackCooldown=.3;return;}this.ammo--;this.attackCooldown=.16;this.shotTime=.12;this.sound=28;const p=this.player,dx=Math.cos(p.angle),dy=Math.sin(p.angle);this.shotEnd={x:p.x,y:p.y};for(let d=.3;d<14;d+=.12){const x=p.x+dx*d,y=p.y+dy*d;if(this.blocked(x,y))break;this.shotEnd={x,y};const z=this.zombies.find(z=>z.hp>0&&Math.hypot(z.x-x,z.y-y)<(p.aiming?.38:.25));if(z){z.hp-=100;z.hit=.25;this.kills++;this.say('Shot landed. The neighborhood heard that.');break;}}}
 attack(){if(this.driving||this.paused||this.dead||this.won||this.attackCooldown>0)return;if(this.weapon==='rifle'){this.fire();return;}if(this.player.stamina<12){this.say('Too exhausted. Catch your breath.');return;}this.player.stamina-=12;this.attackCooldown=.55;this.attackTime=ATTACK_DURATION;this.sound=12;let hit=false;for(const z of this.zombies){if(z.hp<=0)continue;const d=Math.hypot(z.x-this.player.x,z.y-this.player.y);if(d<1.9){z.hp-=55;z.hit=.25;z.pushX=(z.x-this.player.x)/(d||1)*5;z.pushY=(z.y-this.player.y)/(d||1)*5;hit=true;if(z.hp<=0){this.kills++;this.say('One less. Keep moving.');}}}return hit;}
 vehicleBlocked(x:number,y:number){return this.blocked(x,y)||this.houses.some(h=>x>h.x-.4&&x<h.x+h.w+.4&&y>h.y-.4&&y<h.y+h.d+.4);}
 toggleVehicle(){if(this.paused||this.dead||this.won)return;if(!this.driving){if(Math.hypot(this.player.x-this.vehicle.x,this.player.y-this.vehicle.y)>3.5){this.say('Move closer to the green station wagon, then press F.');return;}this.driving=true;this.player.x=this.vehicle.x;this.player.y=this.vehicle.y;this.player.aiming=false;this.say('W / S · Accelerate / reverse    A / D · Steer    F · Exit');}else{if(Math.abs(this.vehicle.speed)>1){this.say('Stop the car before getting out.');return;}for(const offset of [Math.PI/2,-Math.PI/2,Math.PI,0]){const angle=this.vehicle.angle+offset,x=this.vehicle.x+Math.cos(angle)*2,y=this.vehicle.y+Math.sin(angle)*2;if(!this.vehicleBlocked(x,y)){this.driving=false;this.vehicle.speed=0;this.player.x=x;this.player.y=y;this.say('You step out of the station wagon.');return;}}this.say('No clear space to get out.');}}
 drive(dt:number,steer:number,throttle:number){const v=this.vehicle;v.speed+=throttle*9*dt;v.speed*=Math.exp(-dt*(throttle?.25:2.2));v.speed=Math.max(-5,Math.min(15,v.speed));v.angle+=steer*1.9*dt*Math.min(1,Math.abs(v.speed)/3)*(v.speed<0?-1:1);const dx=Math.cos(v.angle)*v.speed*dt,dy=Math.sin(v.angle)*v.speed*dt,steps=Math.max(1,Math.ceil(Math.hypot(dx,dy)/.12));for(let i=0;i<steps;i++){const x=v.x+dx/steps,y=v.y+dy/steps;let blocked=false;for(const forward of [-1.4,0,1.4])for(const side of [-.65,.65])if(this.vehicleBlocked(x+Math.cos(v.angle)*forward-Math.sin(v.angle)*side,y+Math.sin(v.angle)*forward+Math.cos(v.angle)*side))blocked=true;if(blocked){v.speed=0;break;}v.x=x;v.y=y;}this.player.x=v.x;this.player.y=v.y;this.player.angle=v.angle;this.sound=Math.max(this.sound,18);}
 canLoot(crate:LootCrate){if(this.driving||this.dead||this.won||Math.hypot(this.player.x-crate.x,this.player.y-crate.y)>3||this.inside(this.player)!==this.inside(crate))return false;for(let t=.1;t<1;t+=.1)if(this.blocked(this.player.x+(crate.x-this.player.x)*t,this.player.y+(crate.y-this.player.y)*t))return false;return true;}
 loot(crateId:string,itemId?:string){const crate=this.crates.find(c=>c.id===crateId);if(!crate||this.paused||!this.canLoot(crate)){this.say('Move closer to the crate to collect supplies.');return 0;}let taken=0;for(const item of crate.items){if(itemId&&item.id!==itemId)continue;if(item.quantity<=0)continue;const quantity=item.quantity;if(item.kind==='Ammo')this.reserve+=quantity;else this.bag[item.kind]=(this.bag[item.kind]||0)+quantity;item.quantity=0;taken+=quantity;}this.say(taken?`Packed ${taken} supplies. Open I to organize your inventory.`:'This crate is empty.');return taken;}
 interact(){if(this.driving||this.paused||this.dead||this.won)return;const h=this.nearHouse();if(!h){this.say('Get closer to a front door to interact.');return;}if(!h.door){h.door=true;this.say(`${h.name} · Door opened. Search inside.`);return;}if(this.inside(this.player)===h){if(h.searched){this.say('Nothing left here. Check another house.');return;}h.searched=true;this.searched++;for(const item of h.loot)this.bag[item]=(this.bag[item]||0)+1;this.say('Found '+h.loot.join(', ')+'. Supplies packed.');}else{h.door=false;this.say('Door closed.');}}
 use(item:string){if(this.dead||this.won)return;if(!this.bag[item]){this.say(`No ${item.toLowerCase()} left. Search the houses.`);return;}if(item==='Beans'){this.player.hunger=Math.min(100,this.player.hunger+32);this.say('A cold meal. It will do.');}else if(item==='Water'){this.player.thirst=Math.min(100,this.player.thirst+40);this.say('You drink some clean water.');}else if(item==='Bandage'){if(this.player.hp>=100){this.say('No wounds to dress. Save the bandage.');return;}this.player.hp=Math.min(100,this.player.hp+35);this.say('Wounds dressed. Keep them clean.');}else if(item==='Plank'){const h=this.inside(this.player);if(!h){this.say('Enter a house before securing it.');return;}if(this.bag.Plank<2){this.say('You need 2 planks to secure a shelter.');return;}if(this.searched<2){this.say('Search at least 2 houses before settling down.');return;}this.bag.Plank--;this.barricaded=true;h.door=false;this.won=true;this.say('A door between you and the world. Safe, for tonight.');}this.bag[item]--;}
}
