import {RECIPES,SKILLS,type Skill,type BuildKind} from './content';
import type {Simulation} from './sim';
import {pointIn,carContains} from './collision';
export type Construction={id:number;x:number;y:number;floor:number;kind:BuildKind;hp:number;created:number;used:number;activeUntil:number};
export class Survival{
 xp=Object.fromEntries(Object.keys(SKILLS).map(k=>[k,0])) as Record<Skill,number>;buildings:Construction[]=[];serial=0;restUntil=0;
 constructor(public s:Simulation){}
 level(skill:Skill){return Math.min(5,Math.floor(Math.sqrt(this.xp[skill]/30)));}
 gain(skill:Skill,amount:number){this.xp[skill]+=amount;}
 near(kind?:BuildKind){const p=this.s.player;return this.buildings.find(b=>(!kind||b.kind===kind)&&b.floor===p.floor&&Math.hypot(b.x-p.x,b.y-p.y)<2.8&&this.s.inside(b)===this.s.inside(p));}
 solid(b:Construction){return {x:b.x-.5,y:b.y-.5,w:1,d:1,height:b.kind==='wall'?1.8:b.kind==='bench'?.9:.65,kind:b.kind};}
 placement(){const p=this.s.player;return {x:Math.round(p.x+Math.cos(p.angle)*1.8),y:Math.round(p.y+Math.sin(p.angle)*1.8),floor:p.floor};}
 reason(id:string){const r=RECIPES[id],s=this.s;if(!r)return 'Unknown recipe';if(s.driving||s.dead||s.stairTravel)return 'Stand on solid ground first';if(this.level(r.skill)<r.level)return `Requires ${SKILLS[r.skill]} ${r.level}`;if(r.tool&&!s.bag[r.tool])return `Requires ${r.tool} (reusable)`;if(r.station&&!this.near(r.station))return `Stand near a ${r.station==='fire'?'cooking fire':'workbench'}`;for(const [k,n] of Object.entries(r.cost))if((s.bag[k]||0)<n)return `Need ${n} ${k}`;
 if(r.build){const p=this.placement(),home=s.inside(s.player);if((r.build==='fire'||r.build==='barrel')&&home)return 'Build this outdoors';if(s.inside(p)!==home)return 'Choose open space on this side of the wall';for(const dx of [-.55,0,.55])for(const dy of [-.55,0,.55])if(s.blocked(p.x+dx,p.y+dy,p.floor,home))return 'Not enough clear space ahead';if(s.vehicles.some(v=>carContains(v,p.x,p.y,.8))||s.zombies.some(z=>z.hp>0&&(z.floor||0)===p.floor&&Math.hypot(z.x-p.x,z.y-p.y)<1))return 'Placement is occupied';if(home&&(home.floors||1)>1&&p.x>home.x+home.w-3.5&&p.y>home.y+home.d-3.6)return 'Keep the staircase clear';if(home&&Math.hypot(p.x-(home.x+home.w/2),p.y-(home.y+home.d))<1.4)return 'Keep the doorway clear';}return '';}
 craft(id:string){const problem=this.reason(id);if(problem){this.s.say(problem);return;}const r=RECIPES[id];for(const [k,n]of Object.entries(r.cost))this.s.bag[k]-=n;if(r.output)this.s.bag[r.output]=(this.s.bag[r.output]||0)+(r.amount||1);if(r.build)this.buildings.push({id:this.serial++,...this.placement(),kind:r.build,hp:140+this.level('carpentry')*40,created:this.s.elapsed,used:this.s.elapsed,activeUntil:0});this.gain(r.skill,12);this.s.say(r.name+' completed.');}
 dismantle(){const b=this.near();if(!b)return;const recipe=Object.values(RECIPES).find(r=>r.build===b.kind);if(recipe)for(const [k,n]of Object.entries(recipe.cost))this.s.bag[k]=(this.s.bag[k]||0)+Math.floor(n/2);this.buildings=this.buildings.filter(v=>v!==b);this.s.say('Dismantled structure. Recovered some materials.');}
 interact(){const b=this.near();if(!b)return false;const s=this.s;if(b.kind==='barrel'){if(s.elapsed-b.used<120)s.say('Water collector is filling. Check back soon.');else{s.bag.Water=(s.bag.Water||0)+1;b.used=s.elapsed;s.say('Collected a bottle of water.');}}else if(b.kind==='bed'){this.restUntil=s.elapsed+8;s.say('Resting for 8 seconds. Moving or nearby danger interrupts rest.');}else if(b.kind==='lure'){b.activeUntil=s.elapsed+20;s.say('Noise lure activated for 20 seconds.');}else s.say(b.kind==='wall'?'Wooden barricade · '+Math.ceil(b.hp)+' durability':'Press B to craft at this station.');return true;}
 update(dt:number){const s=this.s;if(this.restUntil>s.elapsed){if(s.player.moving||s.zombies.some(z=>z.hp>0&&z.alert&&Math.hypot(z.x-s.player.x,z.y-s.player.y)<6))this.restUntil=0;else{s.player.stamina=Math.min(200,s.player.stamina+dt*12);s.player.hp=Math.min(100,s.player.hp+dt);}}for(const b of this.buildings){for(const z of s.zombies){if(z.hp<=0||(z.floor||0)!==b.floor)continue;if(b.activeUntil>s.elapsed&&Math.hypot(z.x-b.x,z.y-b.y)<15){const d=Math.hypot(z.x-b.x,z.y-b.y);if(d>1)s.move(z,(b.x-z.x)/d*dt*1.5,(b.y-z.y)/d*dt*1.5);}if(z.alert&&Math.hypot(z.x-b.x,z.y-b.y)<1.3)b.hp-=dt*8;}}this.buildings=this.buildings.filter(b=>b.hp>0);}
}
