import {GUNS,RECIPES,SKILLS,type GunKind,type Skill} from './content';
import {ITEM_INFO} from './inventory';
import {itemArt} from './sprite-assets';
import type {Simulation} from './sim';
type View={tab:string;category:string;query:string;ready:boolean;sort:string;selected:string;quantity:number;favorites:Set<string>};
const views=new WeakMap<Simulation,View>();
function state(s:Simulation){let v=views.get(s);if(!v){v={tab:'craft',category:'all',query:'',ready:false,sort:'name',selected:'bandage',quantity:1,favorites:new Set()};views.set(s,v);}return v;}
const escape=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const info=(key:string)=>ITEM_INFO[key as keyof typeof ITEM_INFO];
const art=(key:string)=>itemArt(info(key)?.icon||'wood')||'<span class="craft-symbol">◇</span>';
function maximum(s:Simulation,id:string){const r=RECIPES[id];if(!r||s.survival.reason(id))return 0;return r.build?1:Math.min(99,...Object.entries(r.cost).map(([k,n])=>Math.floor((s.bag[k]||0)/n)));}
export function workshop(s:Simulation){const v=state(s),sv=s.survival;
 const tabs=`<nav class="craft-tabs" aria-label="Workshop sections">${[['craft','Crafting'],['arsenal','Arsenal'],['skills','Skills']].map(([id,label])=>`<button data-tab="${id}" aria-pressed="${v.tab===id}">${label}</button>`).join('')}<span>WORLD PAUSED · B / ESC TO CLOSE</span></nav>`;
 if(v.tab==='arsenal')return `<div class="craft-workspace">${tabs}<div class="craft-secondary"><h3>Your firearms</h3><p>Use found firearms in inventory to unlock them. All firearms share ammunition.</p>${s.ownedGuns.map(k=>`<button class="craft-arsenal" data-gun="${k}">${art('Pistol')}<span><strong>${GUNS[k].name}${s.gun===k?' · Equipped':''}</strong><small>${GUNS[k].desc}</small><small>${GUNS[k].capacity} rounds · ${GUNS[k].damage} damage</small></span></button>`).join('')}</div></div>`;
 if(v.tab==='skills')return `<div class="craft-workspace">${tabs}<div class="craft-secondary"><h3>Learn by doing</h3><p>Craft, repair, cook, heal, shoot and scavenge to develop your skills.</p>${Object.entries(SKILLS).map(([key,name])=>{const k=key as Skill,l=sv.level(k);return `<div class="craft-skill"><strong>${name}<span>Level ${l} / 5</span></strong><progress max="${(l+1)**2*30-l*l*30}" value="${l===5?330:sv.xp[k]-l*l*30}"></progress><small>${Math.floor(sv.xp[k])} XP</small></div>`;}).join('')}</div></div>`;
 const categories=[['all','All recipes'],['favorites','★ Favorites'],['construction','Construction'],['carpentry','Carpentry'],['mechanics','Mechanics'],['cooking','Cooking'],['firstaid','First aid']];
 let entries=Object.entries(RECIPES).filter(([id,r])=>(v.category==='all'||v.category==='favorites'&&v.favorites.has(id)||v.category==='construction'&&r.build||r.skill===v.category)&&(!v.ready||!sv.reason(id))&&(`${r.name} ${r.desc}`).toLowerCase().includes(v.query.toLowerCase()));
 entries.sort((a,b)=>v.sort==='ready'?(Number(!!sv.reason(a[0]))-Number(!!sv.reason(b[0]))||a[1].name.localeCompare(b[1].name)):a[1].name.localeCompare(b[1].name));
 if(!entries.some(([id])=>id===v.selected))v.selected=entries[0]?.[0]||'';
 const r=RECIPES[v.selected],max=r?maximum(s,v.selected):0;v.quantity=Math.max(1,Math.min(v.quantity,max||1));
 const requirement=(key:string,n:number,tool=false)=>{const have=s.bag[key]||0;return `<div class="craft-ingredient ${have>=n?'available':'missing'}">${art(key)}<span>${escape(info(key)?.name||key)}<small>${have} / ${n}${tool?' · kept':''}</small></span></div>`;};
 const detail=r?`<header class="craft-detail-title">${art(r.output||'Plank')}<div><h3>${r.name}</h3><span class="${sv.reason(v.selected)?'missing':'available'}">${sv.reason(v.selected)||'Ready to craft'}</span></div><button id="craft-favorite" aria-label="Toggle favorite" aria-pressed="${v.favorites.has(v.selected)}">${v.favorites.has(v.selected)?'★':'☆'}</button></header><div class="craft-detail-scroll"><p>${r.desc}</p><section><h4>Required items</h4><div class="craft-ingredients">${Object.entries(r.cost).map(([k,n])=>requirement(k,n*v.quantity)).join('')}${r.tool?requirement(r.tool,1,true):''}</div></section><section><h4>Requirements</h4><p class="${sv.level(r.skill)>=r.level?'available':'missing'}">${SKILLS[r.skill]} ${r.level} · Your level: ${sv.level(r.skill)}</p>${r.station?`<p class="${sv.near(r.station)?'available':'missing'}">Nearby ${r.station==='fire'?'cooking fire':'workbench'}</p>`:''}</section><section><h4>Output</h4><div class="craft-ingredient">${art(r.output||'Plank')}<span>${r.output?info(r.output)?.name||r.output:r.name}<small>× ${(r.amount||1)*v.quantity}${r.build?' · Place on highlighted tile ahead':''}</small></span></div></section></div><footer class="craft-actions"><div class="craft-quantity"><label for="craft-quantity">Quantity</label><input id="craft-quantity" type="number" min="1" max="${max||1}" value="${v.quantity}" ${r.build?'disabled':''}><button id="craft-max" ${!max||r.build?'disabled':''}>MAX</button><small>+${12*v.quantity} ${SKILLS[r.skill]} XP</small></div><button class="craft-submit" id="craft-submit" ${!max?'disabled':''}>${r.build?'BUILD':'CRAFT'} ${v.quantity>1?'× '+v.quantity:''}</button></footer>`:'<div class="craft-empty">No matching recipes.<small>Try another category or clear your filters.</small></div>';
 return `<div class="craft-workspace">${tabs}<div class="craft-columns"><aside class="craft-categories" aria-label="Recipe categories">${categories.map(([id,label])=>`<button data-category="${id}" aria-pressed="${v.category===id}">${label}</button>`).join('')}${sv.near()?'<button id="dismantle" class="craft-dismantle">Dismantle nearby<small>Recover half the materials</small></button>':''}</aside><section class="craft-browser"><div class="craft-filters"><input id="craft-search" type="search" placeholder="Search recipes…" aria-label="Search recipes" value="${escape(v.query)}"><select id="craft-sort" aria-label="Sort recipes"><option value="name" ${v.sort==='name'?'selected':''}>Recipe name</option><option value="ready" ${v.sort==='ready'?'selected':''}>Ready first</option></select><label><input id="craft-ready" type="checkbox" ${v.ready?'checked':''}> Can craft</label><small>${entries.length} recipes</small></div><div class="craft-list" aria-label="Recipes">${entries.map(([id,r])=>`<button data-recipe="${id}" aria-pressed="${id===v.selected}">${art(r.output||'Plank')}<span><strong>${v.favorites.has(id)?'★ ':''}${r.name}</strong><small class="${sv.reason(id)?'missing':'available'}">${SKILLS[r.skill]} ${r.level} · ${sv.reason(id)?'Requirements missing':'Ready'}</small></span><span class="craft-chevron">›</span></button>`).join('')}</div></section><section class="craft-detail" aria-label="Recipe details">${detail}</section></div><div class="craft-status" role="status">${s.messageTime>0?escape(s.message):'Select a recipe to see its ingredients and requirements.'}</div></div>`;
}
export function bindWorkshop(root:HTMLElement,s:Simulation,redraw:()=>void){const v=state(s);
 const refresh=()=>{const list=root.querySelector('.craft-list')?.scrollTop||0;redraw();const el=root.querySelector('.craft-list');if(el)el.scrollTop=list;};
 root.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.onclick=()=>{v.tab=b.dataset.tab!;redraw();});
 root.querySelectorAll<HTMLButtonElement>('[data-category]').forEach(b=>b.onclick=()=>{v.category=b.dataset.category!;redraw();});
 root.querySelectorAll<HTMLButtonElement>('[data-recipe]').forEach(b=>b.onclick=()=>{v.selected=b.dataset.recipe!;v.quantity=1;refresh();});
 const search=root.querySelector<HTMLInputElement>('#craft-search');if(search)search.oninput=()=>{v.query=search.value;redraw();root.querySelector<HTMLInputElement>('#craft-search')?.focus();};
 const ready=root.querySelector<HTMLInputElement>('#craft-ready');if(ready)ready.onchange=()=>{v.ready=ready.checked;redraw();};
 const sort=root.querySelector<HTMLSelectElement>('#craft-sort');if(sort)sort.onchange=()=>{v.sort=sort.value;redraw();};
 root.querySelector('#craft-favorite')?.addEventListener('click',()=>{v.favorites.has(v.selected)?v.favorites.delete(v.selected):v.favorites.add(v.selected);refresh();});
 const quantity=root.querySelector<HTMLInputElement>('#craft-quantity');if(quantity)quantity.onchange=()=>{v.quantity=Math.max(1,Math.min(maximum(s,v.selected)||1,Math.floor(Number(quantity.value)||1)));refresh();};
 root.querySelector('#craft-max')?.addEventListener('click',()=>{v.quantity=maximum(s,v.selected)||1;refresh();});
 root.querySelector('#craft-submit')?.addEventListener('click',()=>{const id=v.selected,n=Math.min(v.quantity,maximum(s,id));for(let i=0;i<n;i++){if(s.survival.reason(id))break;s.survival.craft(id);}refresh();});
 root.querySelector('#dismantle')?.addEventListener('click',()=>{s.survival.dismantle();refresh();});
 root.querySelectorAll<HTMLButtonElement>('[data-gun]').forEach(b=>b.onclick=()=>{s.selectGun(b.dataset.gun as GunKind);refresh();});
}
